// entorno-candidato/plataforma-existente/frontend-react/src/App.tsx
import { useState } from "react";
import Ficha from "./pantallas/Ficha";
import Reporte from "./pantallas/Reporte";

export default function App() {
  const [pantalla, setPantalla] = useState<"reporte" | "ficha">("reporte");
  const pestaña = (activa: boolean) =>
    `px-4 py-2 text-sm ${activa ? "border-b-2 border-slate-900 font-semibold" : "text-slate-500"}`;
  return (
    <main className="mx-auto max-w-4xl px-6 py-10">
      <h1 className="text-xl font-semibold text-slate-900">Costos por abogado</h1>
      <nav className="mt-4 flex gap-2 border-b border-slate-200">
        <button className={pestaña(pantalla === "reporte")} onClick={() => setPantalla("reporte")}>Reporte</button>
        <button className={pestaña(pantalla === "ficha")} onClick={() => setPantalla("ficha")}>Ficha</button>
      </nav>
      <section className="mt-6">{pantalla === "reporte" ? <Reporte /> : <Ficha />}</section>
    </main>
  );
}

// entorno-candidato/plataforma-existente/frontend-angular/src/app/app.ts
import { Component, signal } from '@angular/core';
import { Ficha } from './ficha';
import { Reporte } from './reporte';

@Component({
  selector: 'app-root',
  imports: [Reporte, Ficha],
  template: `
    <main>
      <h1>Costos por abogado</h1>
      <nav>
        <button [class.activa]="pantalla() === 'reporte'" (click)="pantalla.set('reporte')">Reporte</button>
        <button [class.activa]="pantalla() === 'ficha'" (click)="pantalla.set('ficha')">Ficha</button>
      </nav>
      <section>
        @if (pantalla() === 'reporte') { <app-reporte /> } @else { <app-ficha /> }
      </section>
    </main>
  `,
  styles: `
    main { max-width: 56rem; margin: 0 auto; padding: 2.5rem 1.5rem; font-family: system-ui, sans-serif; color: #0f172a; }
    h1 { font-size: 1.25rem; font-weight: 600; }
    nav { display: flex; gap: .5rem; border-bottom: 1px solid #e2e8f0; margin-top: 1rem; }
    button { background: none; border: none; padding: .5rem 1rem; font-size: .875rem; color: #64748b; cursor: pointer; }
    button.activa { color: #0f172a; font-weight: 600; border-bottom: 2px solid #0f172a; }
    section { margin-top: 1.5rem; }
  `,
})
export class App {
  readonly pantalla = signal<'reporte' | 'ficha'>('reporte');
}
