// entorno-candidato/plataforma-existente/frontend-react/src/pantallas/Ficha.tsx
import { useEffect, useState } from "react";

interface Abogado {
  id: string;
  nombre: string;
  nivel: string;
}

export default function Ficha() {
  const [abogados, setAbogados] = useState<Abogado[]>([]);
  const [seleccionado, setSeleccionado] = useState("A-01");
  const [costoHora, setCostoHora] = useState<number | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch("/api/abogados").then((r) => r.json()).then(setAbogados);
  }, []);

  useEffect(() => {
    setError(null);
    fetch(`/api/abogados/${seleccionado}/costo-hora`)
      .then((respuesta) => {
        if (!respuesta.ok) throw new Error(`Error ${respuesta.status}`);
        return respuesta.json();
      })
      .then((datos) => setCostoHora(datos.costoHora))
      .catch((e: Error) => {
        setCostoHora(null);
        setError(e.message);
      });
  }, [seleccionado]);

  return (
    <div>
      <select className="rounded border border-slate-300 px-3 py-2 text-sm" value={seleccionado}
              onChange={(e) => setSeleccionado(e.target.value)}>
        {abogados.map((a) => <option key={a.id} value={a.id}>{a.nombre} · {a.nivel}</option>)}
      </select>
      {error && <p className="mt-4 text-sm text-red-700">No se pudo calcular el costo. {error}</p>}
      {costoHora !== null && (
        <div className="mt-6 rounded border border-slate-200 p-4">
          <p className="text-sm text-slate-500">Costo por hora</p>
          <p className="text-2xl font-semibold text-slate-900">Bs {costoHora.toFixed(2)}</p>
        </div>
      )}
    </div>
  );
}

// entorno-candidato/plataforma-existente/frontend-angular/src/app/ficha.ts
import { Component, inject, signal } from '@angular/core';
import { DecimalPipe } from '@angular/common';
import { HttpClient } from '@angular/common/http';

interface Abogado {
  id: string;
  nombre: string;
  nivel: string;
}

@Component({
  selector: 'app-ficha',
  imports: [DecimalPipe],
  template: `
    <select [value]="seleccionado()" (change)="elegir($event)">
      @for (a of abogados(); track a.id) { <option [value]="a.id">{{ a.nombre }} · {{ a.nivel }}</option> }
    </select>
    @if (error()) { <p class="error">No se pudo calcular el costo. {{ error() }}</p> }
    @if (costoHora() !== null) {
      <div class="tarjeta">
        <p class="etiqueta">Costo por hora</p>
        <p class="valor">Bs {{ costoHora() | number: '1.2-2' }}</p>
      </div>
    }
  `,
  styles: `
    select { border: 1px solid #cbd5e1; border-radius: .25rem; padding: .5rem .75rem; font-size: .875rem; }
    .error { margin-top: 1rem; color: #b91c1c; font-size: .875rem; }
    .tarjeta { margin-top: 1.5rem; border: 1px solid #e2e8f0; border-radius: .25rem; padding: 1rem; }
    .etiqueta { font-size: .875rem; color: #64748b; margin: 0; }
    .valor { font-size: 1.5rem; font-weight: 600; margin: .25rem 0 0; }
  `,
})
export class Ficha {
  private readonly http = inject(HttpClient);
  readonly abogados = signal<Abogado[]>([]);
  readonly seleccionado = signal('A-01');
  readonly costoHora = signal<number | null>(null);
  readonly error = signal<string | null>(null);

  constructor() {
    this.http.get<Abogado[]>('/api/abogados').subscribe((lista) => this.abogados.set(lista));
    this.cargar();
  }

  elegir(evento: Event) {
    this.seleccionado.set((evento.target as HTMLSelectElement).value);
    this.cargar();
  }

  private cargar() {
    this.error.set(null);
    this.http.get<{ costoHora: number }>(`/api/abogados/${this.seleccionado()}/costo-hora`).subscribe({
      next: (datos) => this.costoHora.set(datos.costoHora),
      error: (e) => {
        this.costoHora.set(null);
        this.error.set(`Error ${e.status}`);
      },
    });
  }
}
